#!/usr/bin/env bash -e

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureaivideo/pcs-remote-monitoring-webui"
# "testing" is the latest dev build, usually matching the code in the "master" branch
DOCKER_TAG="$DOCKER_IMAGE:3.0.0"

docker push $DOCKER_TAG
