FROM ubuntu:18.04

RUN apt-get update && apt-get install -y  wget software-properties-common && apt-get update \
    && wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && add-apt-repository universe \
    && apt-get install -y apt-transport-https libavcodec-dev libavformat-dev libswscale-dev \
    && apt-get update \
    && apt-get install -y aspnetcore-runtime-2.2=2.2.0-1
    