FROM microsoft/dotnet:2.2-runtime-stretch-slim
# Add the libraries needed by OpenCV
RUN apt-get update \
    && apt-get install -y libavcodec-dev  libavformat-dev libswscale-dev \
    && apt-get update
