FROM azureaivideo/aivideoshared:0.0.3 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.2-runtime-stretch-slim
WORKDIR /app
COPY --from=build-env /app/out ./

COPY ./simulated-images/ ./simulated-images/


RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "CameraModule.dll"]