# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import digestor_pb2 as digestor__pb2


class DigestorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDigestor = channel.unary_unary(
        '/digestor.Digestor/GetDigestor',
        request_serializer=digestor__pb2.DigestMessage.SerializeToString,
        response_deserializer=digestor__pb2.DigestedMessage.FromString,
        )


class DigestorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDigestor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DigestorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDigestor': grpc.unary_unary_rpc_method_handler(
          servicer.GetDigestor,
          request_deserializer=digestor__pb2.DigestMessage.FromString,
          response_serializer=digestor__pb2.DigestedMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'digestor.Digestor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
